### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by SoggyCow** [Crashdaemon/ActionFlow#1]
Have the keys work independently from one-another.
Example: Press A every 2 seconds, while pressing B every 10 seconds.

The current setup is having A being pressed every 12 seconds because the keys are reading together.

**Comment by Crashdaemon** [comment]
I designed it to use sequencing actions (Like how a macro works). Having each key act seperately would require it to have a seperate thread for each action which is really inefficient. However, I could add an option to the action editing window to seperate a specific action and create a seperate thread for it.

**Comment by Crashdaemon** [comment]
I have added this feature. I didn't do much testing so lmk if you find any issues.
